



services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    image: ochosteve08/reactform-backend:latest
    container_name: backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    image: ochosteve08/reactform-frontend:latest
    container_name: reactform-frontend
    build:
      context: ./frontend
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
