services:
  backend:
    build: ./backend
    image: ochosteve08/regform-backend:latest
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/regformdb
    networks:
      - app-network
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    image: ochosteve08/regform-frontend:latest
    ports:
      - "8080:80"
    networks:
      - app-network

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data:
