version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - app-network
    volumes:
      - ./frontend:/usr/share/nginx/html

networks:
  app-network:
